// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTravelPages.Data;

namespace TimeTravelPages.Migrations
{
    [DbContext(typeof(TimeTravelContext))]
    partial class TimeTravelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("TimeTravelPages.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Model")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("TimeTravelPages.Data.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CarId");

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("PositionInTime");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("TimeTravelPages.Data.Passenger", b =>
                {
                    b.HasOne("TimeTravelPages.Data.Car", "Car")
                        .WithMany("Passengers")
                        .HasForeignKey("CarId");
                });
#pragma warning restore 612, 618
        }
    }
}
